language: minimal

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed epowei/udagram-api-feed
  - docker tag udagram-api-user epowei/udagram-api-user
  - docker tag udagram-frontend epowei/udagram-frontend
  - docker tag udagram-reverseproxy epowei/udagram-reverseproxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push epowei/udagram-api-feed
  - docker push epowei/udagram-api-user
  - docker push epowei/udagram-frontend
  - docker push epowei/udagram-reverseproxy