apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  aws_access_key_id: QUtJQVU2U1VMTVlOWVFaU1VMN1A=
  aws_secret_access_key: UmY2Z0tPaVJFcXFwRGFrYjZ4djlOZ29LaHp3V09OL1RSRzhQcXJuRw==